// Package resolv provides /etc/resolv.conf management operations.
package resolv

import (
	"fmt"
	"os"
	"strings"
)

// Config represents DNS resolver configuration.
type Config struct {
	Nameservers []string `json:"nameservers"`
	Search      []string `json:"search"`
	Options     []string `json:"options"`
	Domain      string   `json:"domain"`
	SortList    string   `json:"sort_list"`
}

// GetResult is returned by Get.
type GetResult struct {
	Config Config `json:"config"`
}

// SetResult is returned by Set.
type SetResult struct {
	Changed bool   `json:"changed"`
	Error   string `json:"error,omitempty"`
}

// AddNameserverResult is returned by AddNameserver.
type AddNameserverResult struct {
	Changed     bool   `json:"changed"`
	Nameserver  string `json:"nameserver"`
	Error       string `json:"error,omitempty"`
}

// RemoveNameserverResult is returned by RemoveNameserver.
type RemoveNameserverResult struct {
	Changed    bool   `json:"changed"`
	Nameserver string `json:"nameserver"`
	Error      string `json:"error,omitempty"`
}

const resolvConf = "/etc/resolv.conf"

// Get returns the current DNS resolver configuration.
func Get() (GetResult, error) {
	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return GetResult{}, fmt.Errorf("read resolv.conf: %w", err)
	}

	config := Config{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}

		switch fields[0] {
		case "nameserver":
			config.Nameservers = append(config.Nameservers, fields[1])
		case "search":
			config.Search = fields[1:]
		case "domain":
			config.Domain = fields[1]
		case "options":
			config.Options = fields[1:]
		case "sortlist":
			config.SortList = strings.Join(fields[1:], " ")
		}
	}

	return GetResult{Config: config}, nil
}

// Set replaces the entire resolv.conf with the given configuration.
func Set(nameservers, search, options []string, domain string) (SetResult, error) {
	if len(nameservers) == 0 {
		return SetResult{Error: "at least one nameserver is required"}, fmt.Errorf("at least one nameserver is required")
	}

	// Check current config
	current, _ := Get()
	if configsEqual(current.Config, nameservers, search, options, domain) {
		return SetResult{Changed: false}, nil
	}

	var content strings.Builder
	content.WriteString("# Generated by OpsLang\n")

	if domain != "" {
		content.WriteString(fmt.Sprintf("domain %s\n", domain))
	}

	if len(search) > 0 {
		content.WriteString(fmt.Sprintf("search %s\n", strings.Join(search, " ")))
	}

	for _, ns := range nameservers {
		content.WriteString(fmt.Sprintf("nameserver %s\n", ns))
	}

	if len(options) > 0 {
		content.WriteString(fmt.Sprintf("options %s\n", strings.Join(options, " ")))
	}

	if err := os.WriteFile(resolvConf, []byte(content.String()), 0644); err != nil {
		return SetResult{Error: err.Error()}, fmt.Errorf("write resolv.conf: %w", err)
	}

	return SetResult{Changed: true}, nil
}

// AddNameserver adds a nameserver to resolv.conf.
func AddNameserver(ns string) (AddNameserverResult, error) {
	if ns == "" {
		return AddNameserverResult{Error: "nameserver is required"}, fmt.Errorf("nameserver is required")
	}

	// Check if already exists
	current, err := Get()
	if err != nil {
		return AddNameserverResult{Error: err.Error()}, err
	}

	for _, existing := range current.Config.Nameservers {
		if existing == ns {
			return AddNameserverResult{Changed: false, Nameserver: ns}, nil
		}
	}

	// Read current content
	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return AddNameserverResult{Error: err.Error()}, err
	}

	content := strings.TrimRight(string(data), "\n") + "\n"
	content += fmt.Sprintf("nameserver %s\n", ns)

	if err := os.WriteFile(resolvConf, []byte(content), 0644); err != nil {
		return AddNameserverResult{Error: err.Error()}, fmt.Errorf("write resolv.conf: %w", err)
	}

	return AddNameserverResult{Changed: true, Nameserver: ns}, nil
}

// RemoveNameserver removes a nameserver from resolv.conf.
func RemoveNameserver(ns string) (RemoveNameserverResult, error) {
	if ns == "" {
		return RemoveNameserverResult{Error: "nameserver is required"}, fmt.Errorf("nameserver is required")
	}

	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return RemoveNameserverResult{Error: err.Error()}, err
	}

	var lines []string
	found := false
	for _, line := range strings.Split(string(data), "\n") {
		if strings.TrimSpace(line) == fmt.Sprintf("nameserver %s", ns) {
			found = true
			continue
		}
		lines = append(lines, line)
	}

	if !found {
		return RemoveNameserverResult{Changed: false, Nameserver: ns}, nil
	}

	if err := os.WriteFile(resolvConf, []byte(strings.Join(lines, "\n")), 0644); err != nil {
		return RemoveNameserverResult{Error: err.Error()}, fmt.Errorf("write resolv.conf: %w", err)
	}

	return RemoveNameserverResult{Changed: true, Nameserver: ns}, nil
}

// configsEqual checks if the current config matches the desired config.
func configsEqual(current Config, nameservers, search, options []string, domain string) bool {
	if current.Domain != domain {
		return false
	}
	if !strSliceEqual(current.Nameservers, nameservers) {
		return false
	}
	if !strSliceEqual(current.Search, search) {
		return false
	}
	if !strSliceEqual(current.Options, options) {
		return false
	}
	return true
}

func strSliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
